import { Client, Account, Databases } from 'appwrite';

const client = new Client()
    .setEndpoint(process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!)
    .setProject(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!);

export const account = new Account(client);
export const databases = new Databases(client);

// Database and Collection IDs
export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const USERS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID!;
export const PARTNERSHIP_PREFERENCES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PARTNERSHIP_PREFERENCES_COLLECTION_ID!;
export const PARTNERSHIPS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PARTNERSHIPS_COLLECTION_ID!;
export const SHARED_GOALS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_SHARED_GOALS_COLLECTION_ID!;
export const PARTNER_TASKS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PARTNER_TASKS_COLLECTION_ID!;
export const VERIFICATION_REQUESTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_VERIFICATION_REQUESTS_COLLECTION_ID!;
export const PARTNER_NOTIFICATIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PARTNER_NOTIFICATIONS_COLLECTION_ID!;
export const PARTNERSHIP_METRICS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PARTNERSHIP_METRICS_COLLECTION_ID!;
export const EXPERT_PROFILES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_EXPERT_PROFILES_COLLECTION_ID!;
export const EXPERT_TASKS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_EXPERT_TASKS_COLLECTION_ID!;
export const TASK_SUBMISSIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_SUBMISSIONS_COLLECTION_ID!; 
