# Disabled in favor of Appwrite Functions
# name: Check Due Reminders
# on:
#   schedule:
#     # Run every 5 minutes
#     - cron: '*/5 * * * *'
#   workflow_dispatch: # Allow manual trigger
# 
# jobs:
#   check-reminders:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Call Reminder Check API
#         run: |
#           curl -X GET "${{ secrets.NEXTAUTH_URL }}/api/cron/check-reminders" \
#             -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
#             -H "Content-Type: application/json" \
#             -f # Add -f flag to show HTTP errors 